### ISSUE TITLE
boost error when make

### ISSUE THREAD

**Issue by frank2wang87** [ucbrise/clipper#92]
hi, I filed an issues titled by "make can't find the shared_mutex". Dcrankshaw proposed I  need to compile with GCC 5.2 or later.  And now I compile it with GCC 5.4.0 and run into other problems about boost.

 My PC information is
OS: Ubuntu 14.04.3 LTS
gcc:  5.4.0
boost: boost-1.63

[ 73%] Linking CXX executable bench
../libclipper/libclipper.a(selection_policies.cpp.o): In function `void boost::serialization::throw_exception<boost::archive::archive_exception>(boost::archive::archive_exception const&)':
/home/test/tools/boost-1.63/include/boost-1_63/boost/serialization/throw_exception.hpp:36: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
../libclipper/libclipper.a(selection_policies.cpp.o): In function `void boost::archive::save_access::save_primitive<boost::archive::binary_oarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_oarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/test/tools/boost-1.63/include/boost-1_63/boost/archive/detail/oserializer.hpp:89: undefined reference to `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libclipper/libclipper.a(selection_policies.cpp.o): In function `void boost::archive::load_access::load_primitive<boost::archive::binary_iarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_iarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/home/test/tools/boost-1.63/include/boost-1_63/boost/archive/detail/iserializer.hpp:107: undefined reference to `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
../libclipper/libclipper.a(selection_policies.cpp.o): In function `void boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::load_override<boost::archive::class_name_type>(boost::archive::class_name_type&)':
/home/test/tools/boost-1.63/include/boost-1_63/boost/archive/binary_iarchive_impl.hpp:58: undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/frontends/bench] Error 1
make[1]: *** [src/frontends/CMakeFiles/bench.dir/all] Error 2
make: *** [all] Error 2

**Comment by dcrankshaw** [comment]
My guess is that you've only installed the Boost headers. [Some of the Boost libraries](http://www.boost.org/doc/libs/1_61_0/more/getting_started/unix-variants.html#header-only-libraries) we use need to be compiled, including Boost serialization.
