### ISSUE TITLE
make can't find the shared_mutex

### ISSUE THREAD

**Issue by frank2wang87** [ucbrise/clipper#85]
hi, I configured the clipper environments following the instruction on the github.
I could successfully execute the configure command. But when I executed the "make" command, I  came across the following error.
 
 **clipper-develop/src/libclipper/include/clipper/persistent_state.hpp:6:35: fatal error: shared_mutex: No such file or directory**

   Codes of  persistent_state.hpp are following:
  4 #include <atomic>
  5 #include <functional>
  6 #include <shared_mutex> 

A shared_mutex.hpp file is found in path ''boost-1.63/include/boost-1_63/boost/thread/pthread/ . So I modified the include line to "#include <boost/thread/pthread/shared_mutex.hpp> ". But there came another error referred to boost.

So could anyone give me some suggestion?

Thanks.

**Comment by dcrankshaw** [comment]
Hi @frank2wang87,

That `#include <shared_mutex>` in persistent_state.hpp can actually be deleted. Let me know if that fixes your problem.

We removed the dependency on `shared_mutex` because the libc++ in OSX 10.11 and older doesn't support it (see the answers to this [StackOverflow post](http://stackoverflow.com/q/34533764/814642) for details).

**Comment by frank2wang87** [comment]
hi, @dcrankshaw ,

My PC information is
OS: Ubuntu 14.04.3 LTS
gcc: (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

I deleted  #include<shared_mutex> in persistent_state.hpp. But some other errors happened. The following are the details.

[ 42%] Building CXX object src/libclipper/CMakeFiles/clipper.dir/src/query_processor.cpp.o
In file included from /home/test/workspace/clipper-develop/src/libclipper/src/query_processor.cpp:17:0:
/home/test/workspace/clipper-develop/src/libclipper/include/clipper/future.hpp:41:63: **error**: parameter declared ‘auto’
         [num_futures, completion_promise, num_completed](auto result) mutable {
                                                                ^
/home/test/workspace/clipper-develop/src/libclipper/include/clipper/future.hpp: In lambda function:
/home/test/workspace/clipper-develop/src/libclipper/include/clipper/future.hpp:48:18: **error**: ‘result’ was not declared in this scope
           return result.get();
                   ^
/home/test/workspace/clipper-develop/src/libclipper/include/clipper/future.hpp:60:63: **error**: parameter declared ‘auto’
   return future.then([completion_promise, num_completed](auto result) mutable {
             ^
/home/test/workspace/clipper-develop/src/libclipper/include/clipper/future.hpp:105:64: **error**: parameter declared ‘auto’
    return future.then([completion_promise, completed_flag](auto result) mutable {
                                                                 ^

 
In file included from /home/test/workspace/clipper-develop/src/libclipper/include/clipper/selection_policies.hpp:9:0,
/home/test/workspace/clipper-develop/src/libclipper/include/clipper/task_executor.hpp:66:46: **error**: expected primary-expression before ‘>’ token
          rpc_(std::make_unique<rpc::RPCService>()) {
                                              ^
/home/test/workspace/clipper-develop/src/libclipper/include/clipper/task_executor.hpp:66:48: **error**: expected primary-expression before ‘)’ token

 
/home/test/workspace/clipper-develop/src/libclipper/src/query_processor.cpp:300:5: error: parameter declared ‘auto’
](auto) mutable {


/home/test/workspace/clipper-develop/src/libclipper/src/query_processor.cpp:341:9: **error**: parameter declared ‘auto’
](auto) mutable {
         ^
/home/test/workspace/clipper-develop/src/libclipper/src/query_processor.cpp:355:8: **error**: no matching function for call to ‘boost::future<void>::then(clipper    
::QueryProcessor::update(clipper::FeedbackQuery)::__lambda7)’
       });


/home/test/workspace/clipper-develop/src/libclipper/include/clipper/future.hpp:40:5: **error**: no matching function for call to ‘boost::future<clipper::Output>:    
:then(clipper::future::when_all(std::vector<boost::future<T> >, std::shared_ptr<std::atomic<int> >) [with T = clipper::Output]::__lambda0)’
      wrapped_futures.push_back(f->then(
      ^

/home/test/workspace/clipper-develop/src/libclipper/include/clipper/future.hpp:40:5: **error**: no matching function for call to ‘boost::future<bool>::
then(clipper::future::when_all(std::vector<boost::future<T> >, std::shared_ptr<std::atomic<int> >) [with T = bool]::__lambda0)’

/home/test/tools/boost-1.63/include/boost-1_63/boost/thread/future.hpp:4832:3: **error**: no type named ‘type’ in ‘struct boost::result_of<clipper::future::when_all(std::vector<boost::future<T> >, 
std::shared_ptr<std::atomic<int> >) [with T = bool]::__lambda0(boost::future<bool>)>’

**Comment by dcrankshaw** [comment]
Got it. Clipper is built with C++14 so you will need to compile with GCC 5.2 or later.

**Comment by dcrankshaw** [comment]
Closing this issue. If you run into other problems compiling with GCC >= 5.2 please file a new issue.
